config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "products#index"

  resources :products
  resources :order_items
  resource :cart, only: [:show]

  get 'finalize' => 'carts#finalize'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user, optional: true

  before_save :calculate_total

  def calculate_total
    self.total_price = order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def finalize(user)
    self.user_id = user.id
    self.status = 2
    self.save
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity,
  presence: true,
  numericality: { 
    only_integer: true,
    greater_than: 0,
   }

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :description, presence: true

  validates :price,
    presence: true,
    numericality: {
      greater_than: 0
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  
  has_many :orders

  def previous_orders
    self.orders.where(status: 2).includes(order_items: :product)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :admin
  helper_method :current_order

  def admin
    current_user && current_user.admin
  end

  def current_order
    session[:order_id] ? Order.find(session[:order_id]) : Order.new
  end

  def after_sign_out_path_for(users)
    root_path
  end

protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @previous_orders = current_user.previous_orders if current_user
    @order_items = current_order.order_items
  end

  def finalize
    if current_user
      current_order.finalize(current_user)
      session[:order_id] = nil
      redirect_to cart_path
    else
      flash[:alert] = "You need to sign up or sign in to complete your order."
      redirect_to sign_in_path
    end
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end

  def update
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.update_attributes(item_params)
    @order.save
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js
    end
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action except: [:index, :show] do
    redirect_to new_user_session_path unless admin
  end

  def index
    @products = Product.all.sort
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product Saved Sucessfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params.fetch(:id))
    respond_to do |format|
      format.html {  }
      format.js
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product Sucessfully Updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    Product.find(params.fetch(:id)).destroy
    flash[:notice] = "Product Sucessfully Deleted"
    redirect_to root_path
  end


  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def cart_items
    current_order.order_items.length
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/carts/_cart_total.html.erb
<p>Your Total: <%= number_to_currency current_order.total_price %></p>

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>

<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <%= content_tag(:div, id: item.id) do %>
      <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete", remote: true } %></p>
      <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
    <% end %>
  <% end %>
  
  <div id="cart-total">
    <%= render "cart_total" %>
  </div>

  <p><%= link_to "Finalize order", finalize_path %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

<% if @previous_orders %>
  <h3>Your order history:</h3>
  <% @previous_orders.each do |order| %>
    <h4>Order id: <%= order.id %> was completed on: <%= order.updated_at.strftime("%c") %></h4>
    <% order.order_items.each do |item| %>
      <p>Item name: <%= item.product.name %> | Quantity: <%= item.quantity %> | Price: <%= number_to_currency item.product.price %>
    <% end %>
    <p>Total cost: <%= number_to_currency order.total_price %>
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Cart | Total items: #{ cart_items }", cart_path %></li>
      <li><%= link_to "See all products", products_path %></li>
      <% if current_user %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E Commerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <div id="navbarDisplay">
    <%= render "layouts/navbar" %>
  </div>
  <body>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/order_items/create.js.erb
$("#navbarDisplay").html("<%= j render 'layouts/navbar' %>")

app/views/order_items/destroy.js.erb
var deletedItemID = "<%= j "##{params.fetch(:id)}" %>";
$(deletedItemID).remove();
$("#navbarDisplay").html("<%= j render 'layouts/navbar' %>")
$("#cart-total").html("<%= j render "carts/cart_total" %>")

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  Name: <%= f.text_field :name %>
  Description: <%= f.text_field :description %>
  Price: <%= f.text_field :price %>
  Image: <%= f.file_field :image %>
  <br>
  <br>
  <span class="waves-effect waves-light btn">
    <%= f.submit "Submit" %>
  </span>
<% end %>

app/views/products/_show.html.erb
<p><%= @product.description %></p>
<%= image_tag @product.image.url(:thumb) %>

<% if admin %>
  <span class="waves-effect waves-light btn">
    <%= link_to "Update Product", edit_product_path %>
  </span>
<% end %>

app/views/products/edit.html.erb
<h1>Update a Product</h1>

<%= render "form" %>

<br>

<span class="waves-effect waves-light btn">
  <%= link_to "Delete", product_path(@product), data: { confirm: "Are you sure?" }, method: :delete %>
</span>

app/views/products/index.html.erb
<% if admin %>
  <span class="waves-effect waves-light btn">
    <%= link_to "Add Product", new_product_path %>
  </span>
<% end %>

<h3>Products</h3>

<div class="row">

  <div class="section">
    <% @products.each do |product| %>
      <div class="col s4">
        
        <div class="product-name">
          <h4>
            <span class="product-name-text">
              <%= link_to product.name, product_path(product), remote: true %>
            </span>
          </h4>
        </div>

        <div class="product-description" id="<%= product.id %>">
        </div>

        <p><%= number_to_currency product.price %></p>

        <%= form_for @order_item, remote: true do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
        <%= f.number_field :quantity, placeholder: "Quantity" %>
          <span class="waves-effect waves-light btn">
            <%= f.submit "Add to cart" %>
          </span>
        <% end %>

      </div>
    <% end %>
  </div>

</div>

app/views/products/new.html.erb
<h1>Add a Product</h1>

<%= render "form" %>

app/views/products/show.js.erb
var selectedItemID = "<%= j "##{params.fetch(:id)}" %>";
$(selectedItemID).html("<%= j render "show" %>"); 